name: Deployment
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - run: npm install
       - run: npm start

  # test:
  #    runs-on: ubuntu-latest
  #    needs: build
  #    strategy:
  #       matrix:
  #         os: [ubuntu-latest]
  #         node-version: [14.x]
  #       steps:
  #         - uses: actions/checkout@v2
  #         - name: Use Node.js ${{ matrix.node-version }}
  #           uses: actions/setup-node@v1
  #             with:
  #               node-version: ${{ matrix.node-version }}
  #         - name: yarn install & test
  #           run: |
  #             yarn
  #             yarn test
  #           env:
  #             CI: true
