name: Deployment
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - run: npm install
       - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - run: npm install
       - run: npm run test
       
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: homervt/newapp
          tag_with_ref: true

  deploy-to-digitalocean:
    name: Push Docker image to DigitalOcean
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Deploy Container to Digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
        
  # build-image:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #      - uses: actions/checkout@v2
  #      - name: Build image
  #        run: docker build . --file Dockerfile --tag nextjs-blog --label "runnumber=${GITHUB_RUN_ID}"
  #      - name: Log into registry
  #        run
