name: Deployment
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - run: npm install
       - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - run: npm install
       - run: npm run test

  build-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
       - uses: actions/checkout@v2
       - name: Build image
         run: docker build . --file Dockerfile --tag nextjs-blog --label "runnumber=${GITHUB_RUN_ID}"
         run: docker ps images
